### ISSUE TITLE
no favicon

### ISSUE THREAD

**Issue by seanoldham** [slashrocket/hackathon#3]

**Comment by blackdev1l** [comment]
should be the sick slashrocket favicon ?

2015-06-10 16:33 GMT+02:00 Sean Oldham notifications@github.com:

**Comment by seanoldham** [comment]
yeah, this one

https://github.com/slashrocket/slashrocket.github.io/blob/master/images/slashrocketicon.png

**Comment by blackdev1l** [comment]
:+1: will do

**Comment by seanoldham** [comment]
fixed by @blackdev1l's PR
